In [4]:
import numpy as np
import matplotlib as mpl
import numpy.linalg as lng
import math as mt

По условию, матрицы $K$ и $T$ задаются таким образом: 

In [48]:
def K_n(n):
    K = np.full((n, n), 0)
    for j in range(n):
        for k in range(n):
            if k==j:
                K[j][k] = 2
            if abs(j - k)==1:
                K[j][k] = -1
    return K


def T_n(n):
    T = K_n(n)
    T[0][0] = 1
    return T


def C_n(n):
    C = K_n(n)
    C[0][n-1] = -1
    C[n-1][0] = -1
    return C


def B_n(n):
    B = K_n(n)
    B[0][0] = 1
    B[n-1][n-1] = 1
    return B

### Задание 6

Проверим, что $K_3 = A_1 A_1^T$:

In [70]:
def A():
    A = np.full((3, 4), 0)
    for j in range(3):
        for k in range(4):
            if j == k:
                A[j][k] = -1
            if k - j == 1:
                A[j][k] = 1
    return A

In [80]:
print(A().dot(np.transpose(A())))
print()
print(K_n(3))

[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]

[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]


In [88]:
A_1 = np.delete(A(), 0, 1) 
print(A_1.dot(np.transpose(A_1)))
print()
print(T_n(3))

[[ 1 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]

[[ 1 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]


In [97]:
A_2 = np.delete(A(), 1, 1) 
print(A_2.dot(np.transpose(A_2)))
print()
print(B_n(3))
print('При удалении 2го столбца равенство не получаем')

[[ 1  0  0]
 [ 0  1 -1]
 [ 0 -1  2]]

[[ 1 -1  0]
 [-1  2 -1]
 [ 0 -1  1]]
При удалении 2го столбца равенство не получаем


In [103]:
A_3 = np.delete(A_1, 2, 1) 
print(A_3.dot(np.transpose(A_3)))
print()
print(B_n(3))
print('При удалении 3го столбца равенство получаем')

[[ 1 -1  0]
 [-1  2 -1]
 [ 0 -1  1]]

[[ 1 -1  0]
 [-1  2 -1]
 [ 0 -1  1]]
При удалении 3го столбца равенство получаем


### Задание 7

In [105]:
def get_T(n):
  return lng.inv(T_n(n))

In [110]:
print(get_T(3))
print()
print(get_T(4))
print('Совпадают')

[[3. 2. 1.]
 [2. 2. 1.]
 [1. 1. 1.]]

[[4. 3. 2. 1.]
 [3. 3. 2. 1.]
 [2. 2. 2. 1.]
 [1. 1. 1. 1.]]
Совпадают


In [113]:
print(get_T(5))
print('Wolfram сказал, что правильно:)')

[[5. 4. 3. 2. 1.]
 [4. 4. 3. 2. 1.]
 [3. 3. 3. 2. 1.]
 [2. 2. 2. 2. 1.]
 [1. 1. 1. 1. 1.]]
Wolfram сказал, что правильно:)


### Задание 8 

Вычислим $det(K_n)$, $K_n^{-1}$, $det(K_n) \cdot K_n^{-1}$:

In [13]:
def get_det():
  for j in range(2,6):
      print('det(K_', j,') =', round(lng.det(K_n(j))))
get_det()

det(K_ 2 ) = 3
det(K_ 3 ) = 4
det(K_ 4 ) = 5
det(K_ 5 ) = 6


In [16]:
def get_det_inv():
  for j in range(2,6):
      print('det(K_', j,') =', lng.det(lng.inv(K_n(j))))
get_det_inv()

det(K_ 2 ) = 0.3333333333333333
det(K_ 3 ) = 0.25000000000000006
det(K_ 4 ) = 0.2
det(K_ 5 ) = 0.1666666666666666


In [18]:
def get_dot_det():
  for j in range(2,6):
      print('det K', j, '=', lng.det(lng.inv(K_n(j)).dot(K_n(j))))
get_dot_det()

det K 2 = 1.0
det K 3 = 0.9999999999999999
det K 4 = 0.9999999999999997
det K 5 = 1.0


Посчитаем $K_3^{-1}$:

In [20]:
lng.inv(K_n(3)) * 4

array([[3., 2., 1.],
       [2., 4., 2.],
       [1., 2., 3.]])

In [21]:
lng.inv(K_n(4)) * 5

array([[4., 3., 2., 1.],
       [3., 6., 4., 2.],
       [2., 4., 6., 3.],
       [1., 2., 3., 4.]])

Проверяем:

In [44]:
def check(n):
  return (lng.inv(T_n(n)) - lng.inv(K_n(n))) * (n + 1)

def get_rank(check):
  return (lng.matrix_rank(check))

In [45]:
print('Для n = 4:')
print(check(4))
print('Ранг =', get_rank(check(4)))
print()
print('Для n = 3:')
print(check(3))
print('Ранг =', get_rank(check(3)))

Для n = 4:
[[16. 12.  8.  4.]
 [12.  9.  6.  3.]
 [ 8.  6.  4.  2.]
 [ 4.  3.  2.  1.]]
Ранг = 1

Для n = 3:
[[9. 6. 3.]
 [6. 4. 2.]
 [3. 2. 1.]]
Ранг = 1


In [46]:
K_n(3) - T_n(3)

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])